# ==============================================================================
# SGHospitalizacion02 - Configuración para Docker
# ==============================================================================
spring.application.name=SGHospitalizacion-Front

# Servidor
server.address=0.0.0.0
server.port=8082

# URL del backend (SGHospitalizacion01) dentro de la red Docker sghospitalizacion_net
app.backend.base-url=${BACKEND_BASE_URL:http://sgh01-backend:8080}

# Desactivar DevTools en runtime de contenedor
spring.devtools.restart.enabled=false

# Logs
logging.level.com.ug.ec=INFO
logging.level.org.springframework.web=INFO
